config/routes.rb
Rails.application.routes.draw do

  resources :invoices
  resources :purchases
  resources :products
  resources :payments
  root 'home#index'
  devise_for :users
  match '/add_to_shopping_cart', to: 'products#add_to_shopping_cart', via: 'post'
  match '/pay_with_spei', to: 'purchases#pay_with_spei', via: 'post'
  match '/pay_per_window', to: 'purchases#pay_per_window', via: 'post'
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concept.rb
class Concept < ApplicationRecord
  belongs_to :product

end

app/models/invoice.rb
class Invoice < ApplicationRecord
  after_create_commit { InvoiceJob.perform_later self }  
  after_update_commit { InvoiceJob.perform_later self } 
  belongs_to :user
  has_many :concepts

  after_save :clear_redis_cache

  private

    def clear_redis_cache
      $redis.del 'invoices'
    end
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  # Nombre, descripcion y precio  siempre son necesarios
  # description no debe tener mas de 140 carcteres
  # precio debe ser positivo
  validates :name, presence: true
  validates :description, presence: true, length: {maximum: 140}
  validates :price, presence: true, :numericality => { :greater_than => 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Nombre y rol siempre son necesarios
  validates :role, presence: true
  validates :name, presence: true

  has_many :invoices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.role == "admin"
        redirect_to invoices_path
      else
        redirect_to products_path
      end
    else
      redirect_to user_session_path
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  include InvoicesHelper
  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = fetch_invoices_redis
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:creation_date, :end_date, :total, :user_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_shopping_cart
    # Parametros
    product_name = params[:name]
    product_price = params[:priece]
    product_quantity = params[:quantity]

    # Revisa si el carro de compra esta vacio
    # Agrega la compra
    if session[:shopping_cart].nil?
      session[:shopping_cart] = [{ "product_name" => product_name, "product_quantity" => product_quantity, "product_price" => product_price }]
    else
      # Si se compro un producto de nuevo, sustituye los datos
      session[:shopping_cart] <<  { "product_name" => product_name, "product_quantity" => product_quantity, "product_price" => product_price }
    end

    respond_to do |format|
      format.json { render json: 1 }
      format.js
    end
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    # session.delete(:shopping_cart)
    @purchases = session[:shopping_cart] || []
  end

  def pay_with_spei

    target = params[:tarjeta]
    key = params[:codigo]

    total_payment = 0
    session[:shopping_cart].each do |purchase|
      total_payment += purchase['product_quantity'].to_i*purchase['product_price'].to_f
    end

    # Genera factura
    invoice = Invoice.create(creation_date:Date.today,  end_date:Date.today, total: total_payment, user_id: current_user.id, status:"pagada")

    # Genera concepto
    session[:shopping_cart].each do |purchase|
      product_id = Product.find_by_name(purchase['product_name']).id
      Concept.create(quantity:purchase['product_quantity'].to_i, invoice_id:invoice.id, product_id: product_id )
    end

    # Vacia carrito
    session.delete(:shopping_cart)

    # Genera Pago
    Payment.create(payment_date:Date.today, penalty:0.0, invoice_id:invoice.id, card_number:target ,form_of_pay: "spei")

    respond_to do |format|
      format.json { render json: 1 }
      format.js
    end
  end

  def pay_per_window
    total_payment = 0
    session[:shopping_cart].each do |purchase|
      total_payment += purchase['product_quantity'].to_i*purchase['product_price'].to_f
    end

    # Genera factura
    invoice = Invoice.create(creation_date:Date.today,  end_date:Date.today + 2.day, total: total_payment, user_id: current_user.id, status:"pendiente")

    # Genera concepto
    session[:shopping_cart].each do |purchase|
      product_id = Product.find_by_name(purchase['product_name']).id
      Concept.create(quantity:purchase['product_quantity'].to_i, invoice_id:invoice.id, product_id: product_id )
    end

    dias_atraso = rand(0..30)
    multa = (14.2857 * rand(0..30).to_i )
    fecha_pago = Date.today + dias_atraso.day

    # Genera Pago
    payment = Payment.create(payment_date:fecha_pago, penalty: multa, invoice_id:invoice.id, card_number:nil ,form_of_pay: "ventanilla")

    # Vacia carrito
    session.delete(:shopping_cart)

    #InvoiceJobJob.set(wait: 1.day).perform_later(invoice.id)
    InvoiceJobJob.set(wait: 1.minute).perform_later(invoice.id)

    respond_to do |format|
      format.json { render json: payment}
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def fetch_invoices_redis

    # Esta línea solicita redis-server para aceptar cualquier valor asociado con la clave de facturas
    invoices = $redis.get("invoices")

    # esta condición se ejecutará si alguna factura no está disponible en el servidor redis
    if invoices.nil?
      invoices = Invoice.all.to_json
      $redis.set("invoices",invoices)
      $redis.expire("invoices",5.minutes.to_i)
    end

    # Esto convertirá los datos JSON a Ruby Hash
    JSON.load invoices
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/invoices/index.html.erb
<h1>Facturas</h1>

<table id="invoices_table" class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Fecha de emision</th>
      <th scope="col">Fecha de vencimiento</th>
      <th scope="col">Total $</th>
      <th scope="col">Multa</th>
      <th scope="col">Cliente</th>
      <th scope="col">Estado</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td> <%= invoice['id'] %></td>
        <td> <%= invoice['creation_date'] %></td>
        <td> <%= invoice['end_date'] %></td>
        <td> <%= number_to_currency(invoice['total']) %></td>
        <td><%= Payment.find_by_invoice_id(invoice['id'].to_i).penalty %></td>
        <td><%= User.find(invoice['user_id'].to_i).name %></td>
        <td><%= invoice['status'] %></td>
        <td><%= link_to "Ver Detalle",  invoice_path(invoice['id'].to_i) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h3>
        Factura #<%= @invoice.id %>
      </h3>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col">
      <form>
        <div class="form-group">
          <label for="">Estado:</label>
          <input type="text" class="form-control" value="<%= @invoice.status %>" readonly>
        </div>
        <div class="form-group">
          <label for="">Fecha de creacion:</label>
          <input type="text" class="form-control" value="<%= @invoice.creation_date %>" readonly>
        </div>
        <div class="form-group">
          <label for="">Fecha de vencimiento</label>
          <input type="text" class="form-control" value="<%= @invoice.end_date %>" readonly>
        </div>

        <div class="form-group">
          <label for="">Total a pagar:</label>
          <input type="text" class="form-control" value="<%= @invoice.total %>" readonly>
        </div>

        <div class="form-group">
          <label for="">Cliente:</label>
          <input type="text" class="form-control" value="<%= @invoice.user.name %>" readonly>
          <input type="text" class="form-control" value="<%= @invoice.user.email %>" readonly>
        </div>

      </form>
    </div>
    <div class="col">

    </div>
  </div>

  <hr class="invisible">
  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Producto</th>
            <th scope="col">Cantidad</th>
            <th scope="col">Precio</th>
            <th scope="col"></th>
          </tr>
        </thead>

        <tbody>
          <% @invoice.concepts.each do |concept| %>
            <tr>
              <td><%= concept.product.name %></td>
              <td><%= concept.quantity %></td>
              <td><%= concept.product.price %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>
<!--
< %= link_to 'Regresar', invoices_path %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PagosFacturas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <% @home_label = "Tienda" %>
    <% if user_signed_in? %>
      <% if current_user.role == "admin" %>
        <% @home_label = "Facturas"%>
      <% end %>
    <% end %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">APP</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">

            <%= link_to root_path, class: "nav-link" do  %>
              <%= @home_label %>
              <span class="sr-only">(current)</span>
            <% end %>

          </li>

          <% if user_signed_in?  %>
            <% if current_user.role != "admin"  %>
              <li class="nav-item">
                <%= link_to purchases_path, class: "nav-link" do  %>
                  Carrito de Compras
                <% end %>
              </li>
            <% end %>

            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete , class: "nav-link" do  %>
                Salir
              <% end %>
            </li>

          <% end %>

        </ul>

      </div>
    </nav>

    <div class="container">


      <%= yield %>

    </div>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h3>
        Catalago
        <small class="text-muted">Encuentra todo lo que necesites en un mismo lugar</small>
      </h3>
    </div>
  </div>

  <hr class="invisible">

  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Precio</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= product.name %></td>
              <td><%= product.description %></td>
              <td><%= number_to_currency(product.price) %></td>
              <td><%= link_to 'Ver', product  %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h3>
        <%= @product.name %>
        <small class="text-muted"><%= @product.description %></small>
      </h3>
    </div>
  </div>

  <hr>
  
  <div class="row">
    <div class="col">
      <form>
        <div class="form-group">
          <label for=""><%= number_to_currency(@product.price) %></label>
        </div>
        <div class="form-group">
          <label for="">Cantidad</label>
          <input type="number" class="form-control" id="cantidad_requerida" placeholder="cantidad" onkeyup="calculateFullPayment(this)" onkeypress="javascript:return isNumber(event)">
        </div>
      </form>
    </div>
    <div class="col">

    </div>
  </div>

  <div class="row">
    <div class="col">
      <form>
        <label for=""> Total a pagar $: </label>
        <input id="total_a_pagar" type="text" class="form-control" readonly>
      </form>
      <hr class="invisible">
      <button class="btn btn-primary" onclick="addToShoppingCart()">Agregar al carrito</button>
    </div>
    <div class="col">

    </div>
  </div>
</div>

<script type="text/javascript">

  $( document ).ready(function() {
    full_payment.value = price;
    document.getElementById("cantidad_requerida").value = 1;
  });

  // Precio del producto
  var price = parseFloat("<%= number_to_currency(@product.price, :unit => "").sub(',', '') %>")

  // elemento que contiene el pago total
  var full_payment = document.getElementById("total_a_pagar");

  // Nombre del Producto
  var product_name = "<%=  @product.name %>";

  // Validacion para solo aceptar numeros
  function isNumber(evt) {
    var iKeyCode = (evt.which) ? evt.which : evt.keyCode
    if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57)){
      return false;
    }
    return true;
  }

  // Calcula el total a pagar
  // cantidad_de_producto * precio_producto
  function calculateFullPayment(product_quantity){

    if (product_quantity.value.length > 0) {
      if (product_quantity.value < 1) {
        product_quantity.value = 1;
      }
      full_payment.value = (price * product_quantity.value).toFixed(2);
    }else {
      product_quantity.value = 1;
    }
  }

  // Guarda la compra en el carrito de compras
  function addToShoppingCart(){

    product_quantity = document.getElementById("cantidad_requerida").value
    $.ajax({
      type: 'post',
        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      global: false,
      url: '/add_to_shopping_cart',
      data: {
        name: product_name,
        priece: price,
        quantity: product_quantity
      },
      success: function(x) {
        goToHome();
      }
    });
  }

</script>

app/views/purchases/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h3>
        Tu carrito de compras!!
        <small class="text-muted">En esta seccion encontraras todas tus compras acumuladas</small>
      </h3>
    </div>
  </div>

  <hr class="invisible">

  <div class="row">
    <div class="col">
      <% if !@purchases.empty? %>

        <table class="table">
          <thead>
            <tr>
              <th scope="col">Nombre</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Precio</th>
              <th scope="col">Pago</th>
            </tr>
          </thead>
          <tbody>
            <% total_payment = 0 %>
              <% @purchases.each do |purchase| %>
                <tr>
                  <td><%= purchase['product_name'] %></td>
                  <td><%= purchase['product_quantity'] %></td>
                  <td><%= number_to_currency(purchase['product_price'] )%></td>
                  <td><%= number_to_currency(purchase['product_quantity'].to_i*purchase['product_price'].to_f) %></td>
                  <% total_payment += purchase['product_quantity'].to_i*purchase['product_price'].to_f %>
                </tr>
              <% end %>
          </tbody>
        </table>

        <div class="row">
          <div class="col col-md-6 col-sm-12">
            <form>
              <label for=""> Total a pagar $: </label>
              <input  type="text" class="form-control" value="<%= number_to_currency(total_payment) %>" readonly>
            </form>
            <hr class="invisible">

          </div>

          <div class="col col-md-6 col-sm-12">
            <form>
              <label for=""> Metodo de pago: </label><br>
              <button type="button" class="btn btn-primary btn-block" onclick="payWindow();">
                Ventanilla
              </button>
              <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#paymentSpeiModal">
                SPEI
              </button>
            </form>
          </div>
        </div>

      <% else %>
        Aun no compras nada
      <% end %>
    </div>
  </div>
</div>

<!-- Modal Spei -->
<div class="modal fade" id="paymentSpeiModal" tabindex="-1" role="dialog" aria-labelledby="Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Pago con Tarjeta</h5>

      </div>
      <div class="modal-body">

        <form id="formulario_spei" onsubmit="return false" >
          <div class="form-group">
            <label for="Email1">Correo electronico</label>
            <input type="email" class="form-control" id="Email1" aria-describedby="emailHelp" value= "<%= current_user.email %>">
          </div>
          <div class="form-group">
            <label for="creditCardNumber">Numero de tarjeta</label>
            <input type="text" class="form-control" id="creditCardNumber" placeholder="Ej. 857 487 ...">
            <small id="" class="form-text text-muted">
              Contiene 16 digitos
            </small>
          </div>

          <div class="form-group">
            <label for="creditCardKeyNumber">Codigo (3 digito en la parte posterior de su tarjeta)</label>
            <input type="password" class="form-control" id="creditCardKeyNumber" placeholder="...">
            <small id="" class="form-text text-muted">
              Contiene 3 digitos
            </small>
          </div>

          <div class="form-group">
            <label for="">Importe</label>
            <input type="text" class="form-control" id="fullPayment" value="<%= number_to_currency(total_payment) %>">
          </div>

          <button type="submit" onclick="startPaySpei();" class="btn btn-primary">Pagar</button>
        </form>

      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
<!--modal-->

<!-- Modal Ventanilla -->
<div class="modal fade" id="paymentWindowModal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Pago exitoso</h5>
      </div>
      <div class="modal-body">

        <form id="formulario_ventanilla" onsubmit="return false" >

          <div class="form-group">
            <label for="invoiceFolio">Folio</label>
            <input id="folio" type="text" class="form-control" id="fullPayment" value="">
          </div>

          <div class="form-group">
            <label for="">Fecha de pago</label>
            <input type="text" class="form-control" id="fecha_pago_ventanilla" value="<%= number_to_currency(total_payment) %>">
          </div>

          <div class="form-group">
            <label for="">Multa</label>
            <input type="text" class="form-control" id="multa" value="">
          </div>

          <div class="form-group">
            <label for="">Importe</label>
            <input type="text" class="form-control" id="fullPayment_ventanilla" value="<%= number_to_currency(total_payment) %>">
          </div>

          <button type="submit" onclick="goToHome();" class="btn btn-primary">Continuar</button>
        </form>

      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  // window.addEventListener( 'load', function(){

  // Formulario de pago por spei
  function startPaySpei(){

    var tarjeta = document.getElementById("creditCardNumber").value;
    var codigo = document.getElementById("creditCardKeyNumber").value;

    // debe tener exactamente 16 numeros
    if (tarjeta.length != 16 || isNaN(tarjeta) ) {
      return false;
    }

    // debe tener exactamente 3 numeros
    if (codigo.length != 3 || isNaN(codigo) ) {
      return false;
    }

    paySpei(tarjeta)

  }
  // } ) ;

  // continua con la compra
  function paySpei(tarjeta){

    $.ajax({
      type: 'post',
        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      global: false,
      url: '/pay_with_spei',
      data: {
        tarjeta: tarjeta
      },
      success: function(x) {
        goToHome()
      }
    });
  }

  // genera factura y concepto de pago por Ventanilla
  function payWindow(){

    $.ajax({
      type: 'post',
        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      global: false,
      url: '/pay_per_window',
      data: {
      },
      success: function(payment) {
        total_a_pagar = "<%= total_payment %>"
        total_a_pagar = parseFloat(total_a_pagar) + parseFloat(payment.penalty)
        document.getElementById('fullPayment_ventanilla').value = total_a_pagar.toFixed(2);
        document.getElementById("folio").value = payment.invoice_id
        document.getElementById("fecha_pago_ventanilla").value = payment.payment_date
        document.getElementById("multa").value = payment.penalty.toFixed(2);
        $('#paymentWindowModal').modal('show');
      }
    });
  }

</script>